force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Object used to store data about transactions (selling and buying currency)</description>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</description>
    <inlineHelpText>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</inlineHelpText>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Buy_Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</description>
    <inlineHelpText>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</inlineHelpText>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sell_Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Buy_Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <description>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</description>
    <masterLabel>Buy Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sell_Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <description>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</description>
    <masterLabel>Sell Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExchangeRateApp/ExchangeRateTradeNewRecordController.cls
public with sharing class ExchangeRateTradeNewRecordController {

    @AuraEnabled(cacheable=true)
    public static AvailableCurrencies getAvailableCurrencies(){
        try {
            AvailableCurrencies ac = new AvailableCurrencies();
            ac.sellCurrencies.addAll(getPicklistLabels(Trade__c.Sell_Currency__c));
            ac.buyCurrencies.addAll(getPicklistLabels(Trade__c.Buy_Currency__c));
            return ac;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Map<String, Map<String, Decimal>> getExchangeRates(String currencies){
        try {
            ExchangeRatesParams erp = (ExchangeRatesParams) JSON.deserialize(currencies, ExchangeRatesParams.class);
            Set<String> buyCurrencies = new Set<String>();
            buyCurrencies.addAll(erp.buyCurrencies);
            Map<String, Set<String>> currenciesMap = new Map<String, Set<String>> {erp.sellCurrency => buyCurrencies};
            return ExchangeRateService.getInstance().getExchangeRates(currenciesMap);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static List<String> getPicklistLabels(Schema.SObjectField field) {
        List<String> labelsToReturn = new List<String>();
        Schema.DescribeFieldResult dfr = field.getDescribe();
            Schema.sObjectField T = dfr.getSObjectField();
            List<PicklistEntry> entries = T.getDescribe().getPicklistValues();
            for(PicklistEntry pe : entries) {
                labelsToReturn.add(pe.getLabel());
            }
            return labelsToReturn;
    }

    public class AvailableCurrencies {
        @AuraEnabled
        public List<String> buyCurrencies;
        @AuraEnabled
        public List<String> sellCurrencies;

        public AvailableCurrencies() {
            this.buyCurrencies = new List<String>();
            this.sellCurrencies = new List<String>();
        }
    }

    public class ExchangeRatesParams {
        @AuraEnabled
        public String sellCurrency;
        @AuraEnabled
        public List<String> buyCurrencies;

    }
}