force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <description>Object used to store data about transactions (selling and buying currency)</description>
    <label>Trade</label>
    <nameField>
        <label>Trade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <description>Buy amount for transaction</description>
    <inlineHelpText>Buy amount for transaction</inlineHelpText>
    <label>Buy Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <description>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</description>
    <inlineHelpText>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</inlineHelpText>
    <label>Buy Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Buy_Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>Exchange rate for transaction</description>
    <inlineHelpText>Exchange rate for transaction</inlineHelpText>
    <label>Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sell_Amount__c</fullName>
    <description>Sell amount of transaction</description>
    <inlineHelpText>Sell amount of transaction</inlineHelpText>
    <label>Sell Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <description>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</description>
    <inlineHelpText>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</inlineHelpText>
    <label>Sell Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sell_Currencies</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Buy_Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AED</fullName>
    </customValue>
    <customValue>
        <fullName>AFN</fullName>
    </customValue>
    <customValue>
        <fullName>ALL</fullName>
    </customValue>
    <customValue>
        <fullName>AMD</fullName>
    </customValue>
    <customValue>
        <fullName>ANG</fullName>
    </customValue>
    <customValue>
        <fullName>AOA</fullName>
    </customValue>
    <customValue>
        <fullName>ARS</fullName>
    </customValue>
    <customValue>
        <fullName>AUD</fullName>
    </customValue>
    <customValue>
        <fullName>AWG</fullName>
    </customValue>
    <customValue>
        <fullName>AZN</fullName>
    </customValue>
    <customValue>
        <fullName>BAM</fullName>
    </customValue>
    <customValue>
        <fullName>BBD</fullName>
    </customValue>
    <customValue>
        <fullName>BDT</fullName>
    </customValue>
    <customValue>
        <fullName>BGN</fullName>
    </customValue>
    <customValue>
        <fullName>BHD</fullName>
    </customValue>
    <customValue>
        <fullName>BIF</fullName>
    </customValue>
    <customValue>
        <fullName>BMD</fullName>
    </customValue>
    <customValue>
        <fullName>BND</fullName>
    </customValue>
    <customValue>
        <fullName>BOB</fullName>
    </customValue>
    <customValue>
        <fullName>BRL</fullName>
    </customValue>
    <customValue>
        <fullName>BSD</fullName>
    </customValue>
    <customValue>
        <fullName>BTC</fullName>
    </customValue>
    <customValue>
        <fullName>BTN</fullName>
    </customValue>
    <customValue>
        <fullName>BWP</fullName>
    </customValue>
    <customValue>
        <fullName>BYN</fullName>
    </customValue>
    <customValue>
        <fullName>BYR</fullName>
    </customValue>
    <customValue>
        <fullName>BZD</fullName>
    </customValue>
    <customValue>
        <fullName>CAD</fullName>
    </customValue>
    <customValue>
        <fullName>CDF</fullName>
    </customValue>
    <customValue>
        <fullName>CHF</fullName>
    </customValue>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>PLN</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <description>Set of Currencies that are available in our application to be chosen as &apos;BuyCurrency&apos;</description>
    <masterLabel>Buy Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sell_Currencies.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
        <default>true</default>
        <label>EUR</label>
    </customValue>
    <description>Set of Currencies that are available in our application to be chosen as &apos;Sell Currency&apos;</description>
    <masterLabel>Sell Currencies</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ExchangeRateApp/ExchangeRateTradeNewRecordControllerTest.cls
@IsTest
public with sharing class ExchangeRateTradeNewRecordControllerTest {

    @IsTest
    static void shouldReturnExchangeRates() {
        //given
        ExchangeRateTradeNewRecordController.ExchangeRatesParams params = new ExchangeRateTradeNewRecordController.ExchangeRatesParams();
        ExchangeRateAppTestUtils.ExchangeRateProviderMock erpm = new ExchangeRateAppTestUtils.ExchangeRateProviderMock();
        di_Injector.Org.Bindings.set(new di_Module().bind(ExchangeRateProvider.class).toObject(Test.createStub(ExchangeRateProvider.class, erpm)));

        params.sellCurrency = 'EUR';
        params.buyCurrencies = new List<String>();

        //when
        Test.startTest();
        String paramsString = JSON.serialize(params);
        Map<String, Map<String, Decimal>> exchangeRates = ExchangeRateTradeNewRecordController.getExchangeRates(paramsString);
        Test.stopTest();

        //then
        System.assertEquals(3, exchangeRates.get('EUR').keySet().size(), 'Expecting specific number of target currencies');
        System.assert(exchangeRates.get('EUR').containsKey('PLN'), 'Expecting result contains specific value of target currency');
        System.assert(exchangeRates.get('EUR').containsKey('USD'), 'Expecting result contains specific value of target currency');
        System.assert(exchangeRates.get('EUR').containsKey('EUR'), 'Expecting result contains specific value of target currency');
    }

    @IsTest
    static void shouldReturnAvailableCurrencies() {
        //when
        Test.startTest();
        ExchangeRateTradeNewRecordController.AvailableCurrencies availableCurrencies = ExchangeRateTradeNewRecordController.getAvailableCurrencies();
        Test.stopTest();

        //then
        System.assert(availableCurrencies.sellCurrencies.size() > 0, 'Expecting result contains specific value of target currency');
        System.assert(availableCurrencies.buyCurrencies.size() > 0, 'Expecting result contains specific value of target currency');
    }

    @IsTest
    static void shouldInsertTrade() {
        //given
        String TEST_BUY_CURRENCY = 'AMD';
        String TEST_SELL_CURRENCY = 'EUR';
        Decimal TEST_SELL_AMOUNT = 1000;
        Decimal TEST_RATE = 575.1666;
        Decimal TEST_BUY_AMOUNT = 575166.6;
        String inputString = '{"buyAmount":'+ TEST_BUY_AMOUNT + ',"buyCurrency":"'+ TEST_BUY_CURRENCY + '","rate":'+ TEST_RATE + ',"sellAmount":'+ TEST_SELL_AMOUNT + ',"sellCurrency":"'+ TEST_SELL_CURRENCY + '"}';
        
        //when
        Test.startTest();
            Trade__c insertedTrade = ExchangeRateTradeNewRecordController.insertTrade(inputString);
            Test.stopTest();

            //then
            System.assert(insertedTrade.Id != null, 'Expecting trade record was inserted');
            System.assertEquals(insertedTrade.Buy_Amount__c, TEST_BUY_AMOUNT, 'Expecting specific value of Buy Amount');
            System.assertEquals(insertedTrade.Buy_Currency__c, TEST_BUY_CURRENCY, 'Expecting specific value of Buy Currency');
            System.assertEquals(insertedTrade.Rate__c, TEST_RATE, 'Expecting specific value of Test Rate');
            System.assertEquals(insertedTrade.Sell_Amount__c, TEST_SELL_AMOUNT, 'Expecting specific value of Sell Amount');
            System.assertEquals(insertedTrade.Sell_Currency__c, TEST_SELL_CURRENCY, 'Expecting specific value of Sell Currency');

    }

}